# DP-FedStein Step Noise Final JSE Variant Configuration
# This configuration uses gradient-level noise addition with final JSE shrinkage on parameter differences

defaults:
  - defaults
  - _self_

# Override Hydra output directory to use 'out' instead of 'outputs'
hydra:
  run:
    dir: ../../out/${method}/${dataset.name}/${now:%Y-%m-%d-%H-%M-%S}

# Override method to use DP-FedStein
method: dp_fed_stein

# Dataset settings
dataset:
  name: mnist
  client_num: 100
  alpha: 0.1

# Model settings
model:
  name: 2nn

# Training settings
common:
  seed: 42
  join_ratio: 0.1
  global_epoch: 10
  local_epoch: 5
  batch_size: 32

# DP-FedStein specific parameters - Step Noise Final JSE Variant
dp_fed_stein:
  algorithm_variant: "step_noise_final_jse"  # Gradient-level noise + final JSE on param differences
  jse_enabled: true                          # Enable James-Stein estimator
  clip_norm: 1.0                            # Gradient clipping threshold
  sigma: 0.1                                # Noise standard deviation parameter

# Optimizer settings
optimizer:
  name: sgd
  lr: 0.01
  momentum: 0.9