# DP-FedAvg Last Noise Variant Configuration
# This configuration uses parameter-level noise addition (last_noise)

defaults:
  - defaults
  - _self_

# Override Hydra output directory to use 'out' instead of 'outputs'
hydra:
  run:
    dir: ../../out/${method}/${dataset.name}/${now:%Y-%m-%d-%H-%M-%S}

# Override method to use DP-FedAvg Local
method: dp_fedavg_local

# Dataset settings
dataset:
  name: mnist
  client_num: 100
  alpha: 0.1

# Model settings
model:
  name: 2nn

# Training settings
common:
  seed: 42
  join_ratio: 0.1
  global_epoch: 100
  local_epoch: 10
  batch_size: 32

# DP-FedAvg specific parameters - Last Noise Variant
dp_fedavg_local:
  algorithm_variant: "last_noise"  # Parameter-level noise addition
  clip_norm: 1.0                   # Gradient clipping threshold
  sigma: 1                       # Noise standard deviation parameter

# Optimizer settings
optimizer:
  name: sgd
  lr: 0.01
  momentum: 0.9