# DP-SCAFFOLD Step Noise Variant Configuration
# This configuration uses gradient-level noise addition (step_noise) with SCAFFOLD control variates

defaults:
  - defaults
  - _self_

# Override Hydra output directory to use 'out' instead of 'outputs'
hydra:
  run:
    dir: ../../out/${method}/${dataset.name}/${now:%Y-%m-%d-%H-%M-%S}

# Override method to use DP-SCAFFOLD
method: dp_scaffold

# Dataset settings
dataset:
  name: mnist
  client_num: 100
  alpha: 0.1

# Model settings
model:
  name: 2nn

# Training settings
common:
  seed: 42
  join_ratio: 0.01
  global_epoch: 50
  local_epoch: 5
  batch_size: 32

# DP-SCAFFOLD specific parameters - Step Noise Variant
dp_scaffold:
  algorithm_variant: "step_noise"  # Gradient-level noise addition
  clip_norm: 1.0                   # Gradient clipping threshold
  sigma: 0.1                       # Noise standard deviation parameter
  global_lr: 1.0                   # SCAFFOLD global learning rate

# Optimizer settings
optimizer:
  name: sgd
  lr: 0.1
  momentum: 0.9